web:
  restart: always
  build: ./alfred
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /code/alfred/public
  env_file: .env
  command: sh run.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
#   volumes_from:
#     - data
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

# data:
#   restart: always
#   image: busybox
#   volumes:
#     - /var/lib/postgresql
#   command: "true"
